import { writeFileSync } from "node:fs";
import {
  analyzeDirectory,
  defaultClaudeLogDir,
  loadConfig,
  normalizeDirArg,
  parseSince,
  type SessionAggregate,
} from "@kojihq/core";
import { analyzeDirectoryCached, openCacheDb } from "@kojihq/core-sqlite";

export interface ExportOptions {
  since: string;
  format: string;
  dir?: string;
  cache: boolean;
  output?: string;
}

// 2026-05-17 修正案 10 (桐谷推奨 5 位、Referral 自動化): Markdown format 追加
const VALID_FORMATS = ["csv", "json", "markdown"] as const;
type ExportFormat = (typeof VALID_FORMATS)[number];

function parseFormat(input: string): ExportFormat {
  if ((VALID_FORMATS as ReadonlyArray<string>).includes(input)) {
    return input as ExportFormat;
  }
  throw new Error(
    `Invalid --format: "${input}". Expected: ${VALID_FORMATS.join(", ")}`,
  );
}

const CSV_COLUMNS = [
  "sessionId",
  "filePath",
  "startedAt",
  "endedAt",
  "durationMs",
  "assistantTurns",
  "userTurns",
  "sidechainCount",
  "inputTokens",
  "outputTokens",
  "cacheReadTokens",
  "cacheCreateTokens",
  "costUsd",
  "models",
  "tools",
  "modelChanges",
  "latencyP50Ms",
  "latencyP95Ms",
] as const;

function csvEscape(value: string): string {
  if (value.includes(",") || value.includes('"') || value.includes("\n")) {
    return `"${value.replace(/"/g, '""')}"`;
  }
  return value;
}

function aggToCsvRow(a: SessionAggregate): string {
  const cells = [
    a.sessionId,
    a.filePath,
    a.startedAt ?? "",
    a.endedAt ?? "",
    String(a.durationMs),
    String(a.assistantTurns),
    String(a.userTurns),
    String(a.sidechainCount),
    String(a.inputTokens),
    String(a.outputTokens),
    String(a.cacheReadTokens),
    String(a.cacheCreateTokens),
    a.costUsd.toFixed(6),
    JSON.stringify(a.models),
    JSON.stringify(a.tools),
    JSON.stringify(a.modelChanges),
    String(a.latencyP50Ms),
    String(a.latencyP95Ms),
  ];
  return cells.map(csvEscape).join(",");
}

function renderCsv(aggs: SessionAggregate[]): string {
  const lines: string[] = [];
  lines.push(CSV_COLUMNS.join(","));
  for (const a of aggs) lines.push(aggToCsvRow(a));
  return lines.join("\n") + "\n";
}

function renderJson(aggs: SessionAggregate[]): string {
  return (
    JSON.stringify(
      {
        generatedAt: new Date().toISOString(),
        count: aggs.length,
        sessions: aggs,
      },
      null,
      2,
    ) + "\n"
  );
}

/**
 * 2026-05-17 修正案 10 (桐谷推奨、Referral 自動化): Markdown export
 *
 * Zenn / dev.to / GitHub Discussions / blog 等への貼り付け想定、
 * koji-lens summary に近い human-readable 形式 + 集計サマリ。
 */
function renderMarkdown(aggs: SessionAggregate[]): string {
  const lines: string[] = [];
  const total = aggs.reduce(
    (acc, a) => ({
      sessions: acc.sessions + 1,
      durationMs: acc.durationMs + a.durationMs,
      inputTokens: acc.inputTokens + a.inputTokens,
      outputTokens: acc.outputTokens + a.outputTokens,
      cacheReadTokens: acc.cacheReadTokens + a.cacheReadTokens,
      cacheCreateTokens: acc.cacheCreateTokens + a.cacheCreateTokens,
      costUsd: acc.costUsd + a.costUsd,
    }),
    {
      sessions: 0,
      durationMs: 0,
      inputTokens: 0,
      outputTokens: 0,
      cacheReadTokens: 0,
      cacheCreateTokens: 0,
      costUsd: 0,
    },
  );

  const totalTokens =
    total.inputTokens +
    total.outputTokens +
    total.cacheReadTokens +
    total.cacheCreateTokens;
  const cacheReadPct =
    totalTokens > 0
      ? ((total.cacheReadTokens / totalTokens) * 100).toFixed(1)
      : "0.0";
  const hours = (total.durationMs / 1000 / 60 / 60).toFixed(1);

  lines.push(`# Claude Code Usage Report (${aggs.length} sessions)`);
  lines.push("");
  lines.push(`Generated by [koji-lens](https://github.com/etoryoki/koji-lens) at ${new Date().toISOString()}`);
  lines.push("");
  lines.push("## Summary");
  lines.push("");
  lines.push(`- **Sessions**: ${total.sessions}`);
  lines.push(`- **Duration**: ${hours} hours`);
  lines.push(`- **API equivalent cost**: $${total.costUsd.toFixed(2)}`);
  lines.push(`- **Cache read ratio**: ${cacheReadPct}% (cache_read / total tokens)`);
  lines.push("");
  lines.push("## Sessions");
  lines.push("");
  lines.push("| Started | Duration | Cost | Cache% | Top Tool |");
  lines.push("|---|---|---|---|---|");

  for (const a of aggs.slice(0, 50)) {
    const dur = (a.durationMs / 1000 / 60).toFixed(0) + "m";
    const cost = "$" + a.costUsd.toFixed(2);
    const sessionTotal =
      a.inputTokens + a.outputTokens + a.cacheReadTokens + a.cacheCreateTokens;
    const cachePct =
      sessionTotal > 0
        ? ((a.cacheReadTokens / sessionTotal) * 100).toFixed(0) + "%"
        : "0%";
    const topTool =
      Object.entries(a.tools)
        .sort(([, x], [, y]) => y - x)
        .slice(0, 1)[0]?.[0] ?? "-";
    const started = (a.startedAt ?? "").slice(0, 16).replace("T", " ");
    lines.push(`| ${started} | ${dur} | ${cost} | ${cachePct} | ${topTool} |`);
  }
  if (aggs.length > 50) {
    lines.push("");
    lines.push(`_(showing first 50 of ${aggs.length} sessions; use --format csv/json for full data)_`);
  }
  lines.push("");
  return lines.join("\n");
}

export async function exportCommand(opts: ExportOptions): Promise<void> {
  const cfg = loadConfig();
  const dir = normalizeDirArg(opts.dir ?? cfg.logDir ?? defaultClaudeLogDir());
  const format = parseFormat(opts.format);

  const sinceDate = parseSince(opts.since);
  const sinceIso = sinceDate?.toISOString();

  let all: SessionAggregate[];
  if (opts.cache === false) {
    all = await analyzeDirectory(dir);
  } else {
    const cache = openCacheDb();
    try {
      all = await analyzeDirectoryCached(dir, cache.db);
    } finally {
      cache.close();
    }
  }

  const filtered = sinceIso
    ? all.filter((a) => (a.endedAt ?? a.startedAt ?? "") >= sinceIso)
    : all;
  const sorted = [...filtered].sort((a, b) =>
    (b.endedAt ?? "").localeCompare(a.endedAt ?? ""),
  );

  const output =
    format === "csv"
      ? renderCsv(sorted)
      : format === "markdown"
        ? renderMarkdown(sorted)
        : renderJson(sorted);

  if (opts.output) {
    writeFileSync(opts.output, output, "utf8");
    process.stdout.write(
      `Exported ${sorted.length} session(s) to ${opts.output} (${format})\n`,
    );
  } else {
    process.stdout.write(output);
  }
}
